server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          #uri: file:///Users/user/Desktop/etc/git-local-repo
          uri: https://github.com/kh0712/spring-cloud-config.git

management:
  endpoints:
    web:
      exposure:
        include: heath, busrefresh